export type Member = { name:string; surname:string; role:string; summary:string; interests:string[]; contributions?:string[]; image:string; imageAlt:string; website?:string; provisional?:boolean };

export const members: Member[] = [
  { name:"Zhenyu “Bella” Chen", surname:"Chen", role:"AI & software engineering", summary:"Bella develops AI evaluation systems and full-stack research infrastructure that connect research ideas with usable products.", interests:["Agentic-AI evaluation","LLM evaluation","RAG systems","Applied machine learning"], image:"/images/bella.jpg", imageAlt:"Portrait of Zhenyu Bella Chen", website:"https://zchen868.github.io/" },
  { name:"Ruohan “Fleur” Feng", surname:"Feng", role:"Cognitive science & computational modeling", summary:"Ruohan studies cognitive and affective processes using computational modeling, behavioral evidence, and neurophysiological data.", interests:["Affective cognition","Mental health","Human–AI interaction","Behavioral data"], image:"/images/ruohan.png", imageAlt:"Portrait of Ruohan Fleur Feng", website:"https://rfeng77.github.io/" },
  { name:"Yinqi Huang", surname:"Huang", role:"Cognitive neuroscience & embodied intelligence", summary:"Yinqi studies cognition in naturalistic environments through control theory, virtual reality, mobile EEG, and computational models.", interests:["Embodied cognition","Perception & action","Spatial navigation","Human–robot interaction"], image:"/images/yinqi.jpg", imageAlt:"Portrait of Yinqi Huang", website:"https://yinqihuang.github.io/" },
  { name:"Vineet Upadhyan", surname:"Upadhyan", role:"Undergraduate collaborator in software & VR development", summary:"Vineet contributed programming support for interactive research tasks, including driving and virtual-reality experiments.", interests:["Research programming","Driving tasks","Virtual reality"], contributions:["Driving-task implementation","Virtual-reality task implementation"], image:"/images/team/vineet-upadhyan.jpg", imageAlt:"Portrait of Vineet Upadhyan", provisional:true }
].sort((a,b)=>a.surname.localeCompare(b.surname));

export const research = [
  { slug:"embodied-cognition", title:"Embodied Cognition and Control", short:"How perception and action become intelligent behavior.", overview:"We examine how people estimate their state, select actions, detect mismatches, and adapt while moving through dynamic environments. Control-theoretic models connect moment-to-moment behavior with sensory evidence.", questions:["How do predictions guide action under uncertainty?","How are visual and body-based cues integrated?","How does skill change during human–robot interaction?"], methods:["Control theory","Virtual reality","Mobile EEG","Motion tracking","Bayesian modeling"] },
  { slug:"human-ai", title:"Human–AI and Medical-LLM Interaction", short:"How people interpret, challenge, and share responsibility with AI.", overview:"We study human–AI decision-making as a relationship among patients, clinicians, institutions, and computational systems. The goal is to design interfaces, escalation paths, and evaluation criteria around stakeholder needs.", questions:["When should an AI recommendation be questioned?","How should uncertainty be communicated?","Where do responsibility and escalation belong?"], methods:["Stakeholder research","Behavioral experiments","LLM evaluation","Interface prototyping"] },
  { slug:"interactive-systems", title:"Intelligent Interactive Systems", short:"How experimental platforms can sense, model, and adapt.", overview:"We build interactive systems that make embodied behavior measurable: virtual environments, driving tasks, teleoperation studies, and adaptive experimental interfaces. These systems connect behavior and interaction logs to computational models.", questions:["What signals reveal strategy and learning?","How can systems adapt without obscuring agency?","How can research prototypes remain reproducible?"], methods:["Experimental interfaces","Interaction logs","Computational modeling","Adaptive feedback"] }
];

export type Publication = {title:string;authors:string[];year?:number;venue:string;status:"published"|"preprint"|"under-review"|"in-preparation"|"conference";links?:Record<string,string>;featured?:boolean};
export const publications: Publication[] = [
  {title:"Bayesian cue combination best predicts straight-line distance estimation with translated visual landmarks",authors:["Vishwanath, A.","Watson, M. F.","Gin, M. K.","Markham, D. C.","Huang, Y.","Du, Y. K.","Ekstrom, A. D.","& Wilson, R. C."],year:2025,venue:"Neuropsychologia",status:"published",links:{doi:"https://doi.org/10.1016/j.neuropsychologia.2025.109351"},featured:true},
  {title:"The application of the BERTopic model in natural language processing: In-depth text topic modeling",authors:["Ou, Y.","Zhang, P.","Yu, J.","Li, M.","Su, S.","Zhang, M.","Feng, R.","Sun, F.","Wu, J."],year:2025,venue:"ICCECE · IEEE",status:"published"},
  {title:"The association between mindfulness, psychological flexibility, and rumination in predicting mental health and well-being among university students using machine learning and structural equation modeling",authors:["Feng, R.","Mishra, V.","Hao, X.","Verhaeghen, P."],year:2024,venue:"Machine Learning with Applications",status:"published",featured:true},
  {title:"Adaptation and validation of the Mindful Student Questionnaire in Chinese",authors:["Wang, Q.","Wu, Y.","Feng, R.","Hao, X.","Felver, J. C.","Zhang, Y.","Razza, R."],year:2024,venue:"Mindfulness",status:"published"},
  {title:"Leveraging Virtual Reality to Understand Human Spatial Navigation",authors:["Huang, Y."],year:2023,venue:"Nature Reviews Psychology",status:"published",links:{paper:"https://rdcu.be/"},featured:true},
  {title:"Replicability of Two Classic Experiments in Social Psychology: Implicit Association Test and Imagined Contact",authors:["Huang, Y."],year:2020,venue:"Inkblot: Undergraduate Journal of Psychology",status:"published"},
  {title:"An Experimental Investigation of Implicit Emotional Counter-Regulation and Its Neural Correlates Using a Priming Identity Task",authors:["Feng, R.","Yin, S.","Jahanzad, S.","Hao, X.","Apt, L.","Verhaeghen, P."],venue:"In revision at Cognitive, Affective & Behavioral Neuroscience",status:"under-review"},
  {title:"Control theory model predicts human velocity during multi-sensory navigation in virtual reality",authors:["Huang, Y.","Du, Y. K.","Ekstrom, A.","Wilson, R."],year:2024,venue:"Society for Mathematical Psychology Satellite Meeting",status:"conference"},
  {title:"Neural correlates of mismatch detection and integration of visual and body-based cues in virtual reality",authors:["Huang, Y.","Du, Y. K.","Wilson, R.","Ekstrom, A."],year:2023,venue:"Society for Neuroscience",status:"conference"}
];

export const news = [
  {date:"2026 · Mar",category:"Presentation",title:"Ruohan Feng presents work on implicit emotional counter-regulation at SANS."},
  {date:"2025 · Sep",category:"Milestone",title:"Ruohan Feng passes the doctoral preliminary examination."},
  {date:"2025 · May",category:"Teaching",title:"Ruohan Feng teaches her first PSYC 2020 statistics lab session."},
  {date:"2025",category:"Publication",title:"New work on Bayesian cue combination and distance estimation appears in Neuropsychologia."}
];
