export type Member = { name:string; surname:string; role:string; summary:string; interests:string[]; contributions?:string[]; image:string; imageAlt:string; website?:string; provisional?:boolean };

export const members: Member[] = [
  { name:"Yilin Cai", surname:"Cai", role:"Robotics & medical robot systems", summary:"Yilin is a Ph.D. student in Robotics at Georgia Tech. His research spans medical robots, continuum-robot modeling and planning, robotic manipulation, autonomous driving, and SLAM.", interests:["Medical robotics","Continuum robots","Robot manipulation","Motion planning"], image:"/images/team/yilin-cai.jpg", imageAlt:"Portrait of Yilin Cai", website:"https://missinglight.github.io/" },
  { name:"Zhenyu “Bella” Chen", surname:"Chen", role:"AI & software engineering", summary:"Bella develops AI evaluation systems and full-stack research infrastructure that connect research ideas with usable products.", interests:["Agentic-AI evaluation","LLM evaluation","RAG systems","Applied machine learning"], image:"/images/bella.jpg", imageAlt:"Portrait of Zhenyu Bella Chen", website:"https://zchen868.github.io/" },
  { name:"Ruohan “Fleur” Feng", surname:"Feng", role:"Co-lead · Cognitive science & computational modeling", summary:"Ruohan co-leads EmbodiedHi and studies cognitive and affective processes using computational modeling, behavioral evidence, and neurophysiological data.", interests:["Affective cognition","Mental health","Human–AI interaction","Behavioral data"], image:"/images/ruohan.png", imageAlt:"Portrait of Ruohan Fleur Feng", website:"https://rfeng77.github.io/" },
  { name:"Yinqi Huang", surname:"Huang", role:"Co-lead · Cognitive neuroscience & embodied intelligence", summary:"Yinqi co-leads EmbodiedHi and studies cognition in naturalistic environments through control theory, virtual reality, mobile EEG, and computational models.", interests:["Embodied cognition","Perception & action","Spatial navigation","Human–robot interaction"], image:"/images/yinqi.jpg", imageAlt:"Portrait of Yinqi Huang", website:"https://yinqihuang.github.io/" },
  { name:"Vineet Upadhyan", surname:"Upadhyan", role:"Undergraduate collaborator in software & VR development", summary:"Vineet contributed programming support for interactive research tasks, including driving and virtual-reality experiments.", interests:["Research programming","Driving tasks","Virtual reality"], contributions:["Driving-task implementation","Virtual-reality task implementation"], image:"/images/team/vineet-upadhyan.jpg", imageAlt:"Portrait of Vineet Upadhyan", provisional:true }
].sort((a,b)=>a.surname.localeCompare(b.surname));

export const research = [
  { slug:"human-ai", title:"Human–AI and Medical-LLM Interaction", short:"How people interpret, challenge, and share responsibility with AI.", overview:"We study human–AI decision-making as a relationship among patients, clinicians, institutions, and computational systems. The goal is to design interfaces, escalation paths, and evaluation criteria around stakeholder needs.", questions:["When should an AI recommendation be questioned?","How should uncertainty be communicated?","Where do responsibility and escalation belong?"], methods:["Stakeholder research","Behavioral experiments","LLM evaluation","Interface prototyping"] },
  { slug:"interactive-systems", title:"Intelligent Interactive Systems", short:"How experimental platforms can sense, model, and adapt.", overview:"We build interactive systems that make embodied behavior measurable: virtual environments, driving tasks, teleoperation studies, and adaptive experimental interfaces. These systems connect behavior and interaction logs to computational models.", questions:["What signals reveal strategy and learning?","How can systems adapt without obscuring agency?","How can research prototypes remain reproducible?"], methods:["Experimental interfaces","Interaction logs","Computational modeling","Adaptive feedback"] }
];

export type Publication = {title:string;authors:string[];year?:number;venue:string;status:"published"|"preprint"|"under-review"|"in-preparation"|"conference";links?:Record<string,string>;featured?:boolean};
export const publications: Publication[] = [
  {title:"Opt2skill: Imitating dynamically-feasible whole-body trajectories for versatile humanoid loco-manipulation",authors:["Liu, F.","Gu, Z.","Cai, Y.","Zhou, Z.","Zhao, S.","Jung, H.","Ha, S.","Chen, Y.","Xu, D.","& Zhao, Y."],year:2025,venue:"arXiv preprint arXiv:2409.20514",status:"preprint",links:{preprint:"https://arxiv.org/abs/2409.20514"}},
  {title:"Modeling the journey as well as the destination: a control theory account of rotational navigation",authors:["Huang, Y.","Vishwanath, A.","Du, Y. K.","Watson, M. F.","Asiri, O.","Ekstrom, A. D.","& Wilson, R. C."],year:2026,venue:"bioRxiv",status:"preprint",links:{preprint:"https://www.biorxiv.org/content/10.64898/2026.06.02.729319v1"}},
  {title:"Modular Self-Reconfigurable Continuum Robot for General Purpose Loco-Manipulation",authors:["Cai, Y.","Xu, H.","Wang, Y.","Chen, D.","Matusik, W.","Shou, W.","& Chen, Y."],year:2025,venue:"IEEE Robotics and Automation Letters",status:"published",links:{paper:"https://ieeexplore.ieee.org/abstract/document/10829627"}},
  {title:"A Steerable Cross-Axis Notched Continuum Manipulator for Endobronchial Intervention",authors:["Ai, X.","Cai, Y.","Gao, A.","& Chen, W."],year:2024,venue:"IEEE Transactions on Medical Robotics and Bionics",status:"published",links:{paper:"https://ieeexplore.ieee.org/abstract/document/10472618/"}},
  {title:"Bioinspired Rotation Microneedles for Accurate Transdermal Positioning and Ultraminimal-Invasive Biomarker Detection with Mechanical Robustness",authors:["Cai, Y.","Huang, S.","Zhang, Z.","Zhang, J.","Zhu, X.","Chen, X.","& Ding, X."],year:2022,venue:"Research",status:"published",links:{paper:"https://spj.sciencemag.org/journals/research/2022/9869734/"}},
  {title:"Bayesian cue combination best predicts straight-line distance estimation with translated visual landmarks",authors:["Vishwanath, A.","Watson, M. F.","Gin, M. K.","Markham, D. C.","Huang, Y.","Du, Y. K.","Ekstrom, A. D.","& Wilson, R. C."],year:2025,venue:"Neuropsychologia",status:"published",links:{doi:"https://doi.org/10.1016/j.neuropsychologia.2025.109351"},featured:true},
  {title:"The application of the BERTopic model in natural language processing: In-depth text topic modeling",authors:["Ou, Y.","Zhang, P.","Yu, J.","Li, M.","Su, S.","Zhang, M.","Feng, R.","Sun, F.","Wu, J."],year:2025,venue:"ICCECE · IEEE",status:"published"},
  {title:"The association between mindfulness, psychological flexibility, and rumination in predicting mental health and well-being among university students using machine learning and structural equation modeling",authors:["Feng, R.","Mishra, V.","Hao, X.","Verhaeghen, P."],year:2024,venue:"Machine Learning with Applications",status:"published",featured:true},
  {title:"Adaptation and validation of the Mindful Student Questionnaire in Chinese",authors:["Wang, Q.","Wu, Y.","Feng, R.","Hao, X.","Felver, J. C.","Zhang, Y.","Razza, R."],year:2024,venue:"Mindfulness",status:"published"},
  {title:"Leveraging Virtual Reality to Understand Human Spatial Navigation",authors:["Huang, Y."],year:2023,venue:"Nature Reviews Psychology",status:"published",links:{paper:"https://rdcu.be/"},featured:true},
  {title:"An Experimental Investigation of Implicit Emotional Counter-Regulation and Its Neural Correlates Using a Priming Identity Task",authors:["Feng, R.","Yin, S.","Jahanzad, S.","Hao, X.","Apt, L.","Verhaeghen, P."],venue:"In revision at Cognitive, Affective & Behavioral Neuroscience",status:"under-review"},
  {title:"Control theory model predicts human velocity during multi-sensory navigation in virtual reality",authors:["Huang, Y.","Du, Y. K.","Ekstrom, A.","Wilson, R."],year:2024,venue:"Society for Mathematical Psychology Satellite Meeting",status:"conference"},
  {title:"Neural correlates of mismatch detection and integration of visual and body-based cues in virtual reality",authors:["Huang, Y.","Du, Y. K.","Wilson, R.","Ekstrom, A."],year:2023,venue:"Society for Neuroscience",status:"conference"}
  ,{title:"Propagative Distance Optimization for Motion Planning",authors:["Chen, Y.","Xu, J.","Cai, Y.","Wong, T.-W.","Ren, Z.","Choset, H.","& Shi, G."],year:2025,venue:"IEEE International Conference on Robotics and Automation (ICRA)",status:"conference"}
  ,{title:"Multi-Agent Teamwise Cooperative Path Finding and Traffic Intersection Coordination",authors:["Ren, Z.","Cai, Y.","& Wang, H."],year:2024,venue:"IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)",status:"conference"}
  ,{title:"Propagative Distance Optimization for Constrained Inverse Kinematics",authors:["Chen, Y.","Cai, Y.","Xu, J.","Ren, Z.","Shi, G.","& Choset, H."],year:2024,venue:"International Workshop on the Algorithmic Foundations of Robotics (WAFR)",status:"conference",links:{preprint:"https://arxiv.org/abs/2406.11572"}}
  ,{title:"In-Hand Manipulation in Power Grasp: Design of an Adaptive Robot Hand with Active Surfaces",authors:["Cai, Y.","& Yuan, S."],year:2023,venue:"IEEE International Conference on Robotics and Automation (ICRA)",status:"conference",links:{paper:"https://ieeexplore.ieee.org/document/10161516"}}
  ,{title:"Statics Modeling of Discrete Joint Surgical Probes with Tendon-based Stiffening",authors:["Cai, Y.","Orekhov, A.","& Choset, H."],year:2023,venue:"International Symposium on Medical Robotics (ISMR)",status:"conference",links:{paper:"https://ieeexplore.ieee.org/document/10130175"}}
  ,{title:"DytanVO: Joint Refinement of Visual Odometry and Motion Segmentation in Dynamic Environments",authors:["Shen, S.","Cai, Y.","Wang, W.","& Scherer, S."],year:2023,venue:"IEEE International Conference on Robotics and Automation (ICRA)",status:"conference",links:{paper:"https://ieeexplore.ieee.org/document/10161306"}}
];

export const news = [
  {date:"2026 · Mar",category:"Presentation",title:"Ruohan Feng presents work on implicit emotional counter-regulation at SANS."},
  {date:"2025 · Sep",category:"Milestone",title:"Ruohan Feng passes the doctoral preliminary examination."},
  {date:"2025 · May",category:"Teaching",title:"Ruohan Feng teaches her first PSYC 2020 statistics lab session."},
  {date:"2025",category:"Publication",title:"New work on Bayesian cue combination and distance estimation appears in Neuropsychologia."}
];
