import React, { Suspense, lazy, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { members, news, publications, research } from "./data";
import "./styles.css";

const HeroScene = lazy(() => import("./scene/HeroScene"));
const nav = [["Home","/"],["Research","/research/"],["Team","/team/"],["Publications","/publications/"],["News","/news/"]];

function Logo(){return <span className="logo-mark" aria-hidden="true"><i/><i/><b/><em/></span>}
function Shell({children}:{children:React.ReactNode}){
  const [open,setOpen]=useState(false);
  return <><a className="skip" href="#main">Skip to content</a><header><a className="brand" href="/"><Logo/><span>Embodied Human<br/>Intelligence</span></a><button className="menu" aria-expanded={open} aria-controls="nav" onClick={()=>setOpen(!open)}>Menu</button><nav id="nav" data-open={open}>{nav.map(([l,h])=><a key={h} href={h} aria-current={location.pathname===h?"page":undefined}>{l}</a>)}</nav></header>{children}<footer><div><Logo/><h2>Embodied Human<br/>Intelligence</h2></div><div>{nav.map(([l,h])=><a key={h} href={h}>{l}</a>)}</div><small>© 2026 Embodied Human Intelligence</small></footer></>;
}
function Label({n,children}:{n:string;children:React.ReactNode}){return <div className="label"><span>{n}</span>{children}</div>}
function Intro({kicker,title,children}:{kicker:string;title:string;children?:React.ReactNode}){return <section className={`intro ${children?"":"intro-solo"}`}><p className="eyebrow">{kicker}</p><h1>{title}</h1>{children&&<div>{children}</div>}</section>}
function Reveal({children,className=""}:{children:React.ReactNode;className?:string}){const [on,setOn]=useState(false);const ref=React.useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){setOn(true);o.disconnect()}},{threshold:.12});o.observe(el);return()=>o.disconnect()},[]);return <div ref={ref} className={`reveal ${on?"shown":""} ${className}`}>{children}</div>}

function HeroFallback(){return <div className="hero-poster" role="img" aria-label="Abstract human and robot coordinating around a shared task through a continuous feedback loop"><div className="figure human"><i/><b/><span/></div><div className="shared">shared<br/>task</div><div className="figure robot"><i/><b/><span/></div><div className="feedback">perceive · act · adapt</div></div>}
function Home(){return <Shell><main id="main">
  <section className="hero"><div className="hero-copy"><p className="eyebrow">Embodied Human Intelligence</p><h1>Intelligence<br/>takes shape<br/><em>in interaction.</em></h1><p className="lede">We study how people navigate, learn, move, and make decisions with intelligent systems—combining behavioral experiments, computational modeling, neuroscience, and human-centered AI.</p><div className="actions"><a className="button" href="/research/">Explore research ↗</a><a className="text-link" href="/team/">Meet the collaborators →</a></div></div><div className="hero-stage"><Suspense fallback={<HeroFallback/>}><HeroScene/></Suspense><p className="sr-only">A human and a humanoid robot coordinate around a shared object. A moving loop represents reciprocal perception, action, and adaptation.</p></div></section>
  <Reveal><section className="premise"><Label n="01">Our premise</Label><h2>Intelligence emerges through bodies, environments, and computational systems.</h2><p>EmbodiedHi is an interdisciplinary group of collaborators. Its central research themes are led by Yinqi Huang and developed through distinct partnerships across cognition, engineering, health, and AI.</p></section></Reveal>
  <section className="stories"><Label n="02">Research directions</Label>{research.map((r,i)=><Reveal key={r.slug}><article className={`story story-${i+1}`}><div className="story-art" aria-hidden="true"><span>0{i+1}</span><div className="diagram-orbit"><i/><i/><i/></div></div><div><p className="eyebrow">Research direction 0{i+1}</p><h2>{r.title}</h2><p>{r.short}</p><div className="chips">{r.methods.slice(0,3).map(x=><span key={x}>{x}</span>)}</div><a className="text-link" href={`/research/#${r.slug}`}>Read the research story →</a></div></article></Reveal>)}</section>
  <section className="selected"><div><Label n="03">Selected publications</Label>{publications.filter(p=>p.featured).slice(0,3).map(p=><article key={p.title}><time>{p.year}</time><h3>{p.title}</h3><p>{p.venue}</p></article>)}<a className="text-link" href="/publications/">All publications →</a></div><div><Label n="04">Recent news</Label>{news.slice(0,3).map(n=><article key={n.title}><time>{n.date}</time><span className="tag">{n.category}</span><h3>{n.title}</h3></article>)}<a className="text-link" href="/news/">All news →</a></div></section>
  <section className="team-preview"><Label n="05">Collaborators</Label><div>{members.map(m=><a href="/team/" key={m.name}><img src={m.image} alt="" width="220" height="260"/><span>{m.name}<small>{m.role}</small></span></a>)}</div></section>
  </main></Shell>}

function StakeholderDiagram(){return <div className="stakeholders" role="img" aria-label="Patient, clinician, AI system, and health institution share information, escalation, and responsibility around a recommendation"><span>Patient</span><span>Clinician</span><b>Recommendation<br/>+ interface</b><span>AI system</span><span>Health institution</span><small>↗ escalation · ↔ responsibility</small></div>}
function SystemsDiagram(){return <div className="system-map" role="img" aria-label="Experimental interface connects human behavior and interaction logs to a computational model and adaptive feedback"><span>Experimental<br/>interface</span><i>→</i><span>Human<br/>behavior</span><i>→</i><span>Interaction<br/>logs</span><i>→</i><span>Computational<br/>model</span><i>→</i><span>Adaptive<br/>feedback</span></div>}
function Research(){return <Shell><main id="main"><Intro kicker="Research" title="Research directions"/><div className="research-stack">{research.map((r,i)=><section id={r.slug} key={r.slug} className="research-section"><Label n={`0${i+1}`}>Direction</Label><div className="research-title"><h2>{r.title}</h2><p>{r.overview}</p></div>{r.slug==="human-ai"?<StakeholderDiagram/>:<SystemsDiagram/>}<div className="research-meta"><div><h3>Representative questions</h3>{r.questions.map(q=><p key={q}>{q}</p>)}</div><div><h3>Methods</h3><div className="chips">{r.methods.map(m=><span key={m}>{m}</span>)}</div></div></div></section>)}</div></main></Shell>}
function Team(){return <Shell><main id="main"><Intro kicker="People & perspectives" title="Distinct expertise. Shared inquiry."><p>EmbodiedHi brings together collaborators whose individual interests and contributions remain visible.</p></Intro><section className="team-list">{members.map((m,i)=><article key={m.name}><div className="portrait"><img src={m.image} alt={m.imageAlt} width="720" height="840"/></div><div><p className="eyebrow">0{i+1} · {m.role}</p><h2>{m.name}</h2><p className="member-summary">{m.summary}</p><div className="chips">{m.interests.map(x=><span key={x}>{x}</span>)}</div>{m.website&&<a className="text-link" href={m.website} target="_blank" rel="noreferrer">Personal website ↗</a>}</div></article>)}</section></main></Shell>}
const groups=[['published','Published Articles'],['preprint','Preprints'],['under-review','Under Review'],['in-preparation','Manuscripts in Preparation'],['conference','Conference Papers & Presentations']] as const;
function Publications(){const team=["Feng, R.","Huang, Y.","Chen, Z."];return <Shell><main id="main"><Intro kicker="Writing & scholarship" title="Publications"/><div className="pubs">{groups.map(([s,l])=>{const ps=publications.filter(p=>p.status===s).sort((a,b)=>(b.year||0)-(a.year||0));return <section key={s}><header><h2>{l}</h2><span>{String(ps.length).padStart(2,"0")}</span></header>{ps.length?<ol>{ps.map(p=><li key={p.title}><time>{p.year||"—"}</time><div><h3>{p.title}</h3><p>{p.authors.map((a,i)=><React.Fragment key={a}>{team.includes(a)?<strong>{a}</strong>:a}{i<p.authors.length-1?", ":""}</React.Fragment>)}</p><p className="venue">{p.venue}</p>{p.links&&Object.entries(p.links).map(([k,v])=><a className="text-link" href={v} key={k}>{k} ↗</a>)}</div></li>)}</ol>:<p className="empty">No verified entries yet.</p>}</section>})}</div></main></Shell>}
function News(){return <Shell><main id="main"><Intro kicker="Updates" title="News"><p>Verified publications, presentations, milestones, and teaching notes.</p></Intro><section className="news-list">{news.map((n,i)=><article key={n.title}><span>0{i+1}</span><time>{n.date}</time><div><b className="tag">{n.category}</b><h2>{n.title}</h2></div></article>)}</section></main></Shell>}
const path=location.pathname.replace(/\/+$/,"/");const Page=path==="/research/"?Research:path==="/team/"?Team:path==="/publications/"?Publications:path==="/news/"?News:Home;
createRoot(document.getElementById("root")!).render(<Page/>);
